### ISSUE TITLE
all elements don't work - ClassCastException

### ISSUE THREAD

**Issue by lilletech** [vaadin/gwt-polymer-elements#10]
Some elements don't work and give a classcastexception 
exemple : PaperCheckbox, PaperRadioButton, PaperDialog,PaperSlider

error the error in chrome developer tools when using papercheckbox
Uncaught java.lang.ClassCastExceptionsY_g$ @ InternalPreconditions.java:31dOc_g$ @ Cast.java:63Xni_g$ @ PaperCheckbox.java:63Yni_g$ @ PaperCheckbox.java:62Bni_g$ @ PaperRadioButton.java:39Uni_g$ @ PaperCheckbox.java:37Tni_g$ @ PaperCheckbox.java:30Sni_g$ @ PaperCheckbox.java:23Nfi_g$ @ ShowCasePolymer.java:30jyf_g$ @ GwtShowcase.java:225xRc_g$ @ com_00046inovelan_00046gwt_00046showcase_00046GwtShowcase__EntryMethodHolder.java:3initializeModules_0_g$ @ ModuleUtils.java:44fU_g$ @ Impl.java:247iU_g$ @ Impl.java:306(anonymous function) @ Impl.java:72YQc_g$ @ ModuleUtils.java:55(anonymous function) @ JavaClassHierarchySetupUtil.java:24

**Comment by Inovelan** [comment]
Hi there.
I have the same issue.

Regards

**Comment by manolo** [comment]
Have you adding the experimental flag to your compilation or superdevmode run?
-XjsInteropMode JS

It is tested with gwt-2.8.0-SNAPSHOT but might work with gwt-2.7.0

**Comment by lilletech** [comment]
i've set this pom.xml configuration, i'm usingn the gwt-2.8.0-SNAPSHOT

  <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>gwt-maven-plugin</artifactId>
                <version>${gwt.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <module>com.inovelan.gwt.showcase.GwtShowcase</module>
                    <style>OBFUSCATED</style>
                    <logLevel>INFO</logLevel>

<webappDirectory>src/main/resources/gwt</webappDirectory>
                    <persistentunitcachedir>.</persistentunitcachedir>
                    <localWorkers>4</localWorkers>
                    
                    <draftCompile>false</draftCompile>
                    <jsInteropMode>JS</jsInteropMode>
                </configuration>
                <dependencies>
                    <dependency>
                        <groupId>com.google.gwt</groupId>
                        <artifactId>gwt-dev</artifactId>
                        <version>${gwt.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.gwt</groupId>
                        <artifactId>gwt-codeserver</artifactId>
                        <version>${gwt.version}</version>
                    </dependency>
                    <dependency>
                        <groupId>com.google.gwt</groupId>
                        <artifactId>gwt-user</artifactId>
                        <version>${gwt.version}</version>
                    </dependency>
                </dependencies>
            </plugin>

2015-05-29 8:27 GMT+02:00 Manuel Carrasco Moñino notifications@github.com:

> Have you adding the experimental flag to your compilation or superdevmode
> run?
> -XjsInteropMode JS
> 
> It is tested with gwt-2.8.0-SNAPSHOT but might work with gwt-2.7.0
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vaadin/gwt-polymer/issues/10#issuecomment-106706421.

## 

Jimmy Pannier

**Comment by lilletech** [comment]
Thanks i was using the super dev mode without jsInteropMode.

**Comment by j-mi-jim** [comment]
when i use a paper dialog, the first call to the open method giving an exception. (after the calls works)




Uncaught com.google.gwt.event.shared.UmbrellaException: Exception caught: (TypeError) : this.getPolymerElement_11_g$(...).open is not a functionqtc_g$ @ HandlerManager.java:129Y6c_g$ @ Widget.java:129Hjc_g$ @ DomEvent.java:125e7c_g$ @ Widget.java:177Brd_g$ @ DOM.java:1480Ard_g$ @ DOM.java:1419Sxd_g$ @ DOMImplStandard.java:317fU_g$ @ Impl.java:247iU_g$ @ Impl.java:306(anonymous function) @ Impl.java:72




 PaperButton b = new PaperButton("button");
    b.setCenter(true);
    add(b);
    
    b.addClickHandler((ClickEvent event) -> {
      final PaperDialog d = new PaperDialog("Test");
      d.setTransition("core-transition-center");
      d.open();
    });

**Comment by manolo** [comment]
All right.
