### ISSUE TITLE
 [ERROR] Hint: Check that your classpath includes all required source roots

### ISSUE THREAD

**Issue by zak905** [vaadin/gwt-polymer-elements#130]
I got the below error in my project. It was working perfectly with GWT 2.8.0-VC-SNAPSHOT version

``` xml
Ignored 1 unit with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to DEBUG or WARN to see all errors.
[INFO]    Ignored 1 unit with compilation errors in first pass.
[INFO] Compile with -strict or with -logLevel set to TRACE or DEBUG to see all errors.
[INFO]    [ERROR] Errors in 'jar:file:/C:/Users/zakaria/.m2/repository/com/google/gwt/gwt-dev/2.8.0-beta1/gwt-dev-2.8.0-beta1.jar!/com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java'
[INFO]       [ERROR] Line 37: The method captureStackTrace(Object) in the type StackTraceCreator is not applicable for the arguments (JavaScriptException, Object)
[INFO]    Tracing compile failure path for type 'com.google.gwt.lang.Exceptions'
[INFO]       [ERROR] Errors in 'jar:file:/C:/Users/zakaria/.m2/repository/com/google/gwt/gwt-dev/2.8.0-beta1/gwt-dev-2.8.0-beta1.jar!/com/google/gwt/dev/jjs/intrinsic/com/google/gwt/lang/Exceptions.java'
[INFO]          [ERROR] Line 37: The method captureStackTrace(Object) in the type StackTraceCreator is not applicable for the arguments (JavaScriptException, Object)
[INFO]    [ERROR] Hint: Check that the type name 'com.google.gwt.lang.Exceptions' is really what you meant
[INFO]    [ERROR] Hint: Check that your classpath includes all required source roots
```

**Comment by zak905** [comment]
It turns out gwt-dev was on 2.8.0-beta1 version and not on SNAPSHOT.
